database:
  image: "postgres"
  container_name: "database"
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=1234
    - POSTGRES_MULTIPLE_DATABASES=boards,players,games






